/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainSweep.java
 *
 * Created on Dec 25, 2010, 10:17:49 AM
 */

package minesweeper;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Abah
 */
public class MainSweep extends javax.swing.JFrame {

    private boolean isRunning = false;

    private int s = 0, m = 0, h = 0;

    /** Creates new form MainSweep */
    public MainSweep() {
        initComponents();
        //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        //UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");


        ButtonGroup group = new ButtonGroup();
        group.add(mnBeginner);
        group.add(mnIntermediate);
        group.add(mnExpert);
        group.add(mnCustom);

        ActionListener al = new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                setDuration();
            }
        };
        new Timer(1000, al).start();
        this.isRunning = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnToolbar = new javax.swing.JPanel();
        txtTimes = new javax.swing.JTextField();
        btnSmile = new javax.swing.JLabel();
        txtMines = new javax.swing.JTextField();
        pnGame = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        mnBar = new javax.swing.JMenuBar();
        mnGame = new javax.swing.JMenu();
        mnNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnBeginner = new javax.swing.JRadioButtonMenuItem();
        mnIntermediate = new javax.swing.JRadioButtonMenuItem();
        mnExpert = new javax.swing.JRadioButtonMenuItem();
        mnCustom = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnMarks = new javax.swing.JCheckBoxMenuItem();
        mnColor = new javax.swing.JCheckBoxMenuItem();
        mnSound = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnBestTimes = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnContents = new javax.swing.JMenuItem();
        mnSearchHelp = new javax.swing.JMenuItem();
        mnUsingHelp = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minesweeper");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnToolbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        pnToolbar.setPreferredSize(new java.awt.Dimension(400, 50));

        txtTimes.setBackground(new java.awt.Color(0, 0, 0));
        txtTimes.setFont(new java.awt.Font("Digital-7", 1, 22)); // NOI18N
        txtTimes.setForeground(new java.awt.Color(255, 0, 0));
        txtTimes.setText("000");

        btnSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smiley1.png"))); // NOI18N
        btnSmile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSmileMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSmileMouseReleased(evt);
            }
        });

        txtMines.setBackground(new java.awt.Color(0, 0, 0));
        txtMines.setFont(new java.awt.Font("Digital-7", 1, 22)); // NOI18N
        txtMines.setForeground(new java.awt.Color(255, 0, 0));
        txtMines.setText("010");

        javax.swing.GroupLayout pnToolbarLayout = new javax.swing.GroupLayout(pnToolbar);
        pnToolbar.setLayout(pnToolbarLayout);
        pnToolbarLayout.setHorizontalGroup(
            pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToolbarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtMines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnToolbarLayout.setVerticalGroup(
            pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToolbarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMines, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnToolbar, java.awt.BorderLayout.PAGE_START);

        pnGame.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3)));
        pnGame.setLayout(new java.awt.GridLayout(9, 9));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        pnGame.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel4);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel5);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel11);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel12);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel13);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel14);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel15);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel16);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel19);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel17);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel18);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel20);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel21);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel22);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel23);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel24);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel25);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel26);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel28);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel27);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel29);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel31);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        pnGame.add(jLabel32);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel33);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel34);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel35);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel43);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel44);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel46);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel36);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel47);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel45);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel42);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel37);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel38);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel39);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel41);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel48);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel55);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel49);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel50);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel51);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel52);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel53);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel54);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel56);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel57);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel58);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel59);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel60);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel61);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel64);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel62);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel63);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel65);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel66);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel67);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel68);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel69);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel70);

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel71);

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel73);

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel72);

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel74);

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel75);

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel76);

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel77);

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel78);

        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel79);

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel80);

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label1.png"))); // NOI18N
        pnGame.add(jLabel81);

        jPanel1.add(pnGame, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        mnGame.setMnemonic('G');
        mnGame.setText("Game");

        mnNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnNew.setText("New");
        mnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNewActionPerformed(evt);
            }
        });
        mnGame.add(mnNew);
        mnGame.add(jSeparator1);

        mnBeginner.setMnemonic('B');
        mnBeginner.setSelected(true);
        mnBeginner.setText("Beginner");
        mnBeginner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBeginnerActionPerformed(evt);
            }
        });
        mnGame.add(mnBeginner);

        mnIntermediate.setText("Intermediate");
        mnGame.add(mnIntermediate);

        mnExpert.setText("Expert");
        mnGame.add(mnExpert);

        mnCustom.setText("Custom...");
        mnGame.add(mnCustom);
        mnGame.add(jSeparator2);

        mnMarks.setSelected(true);
        mnMarks.setText("Marks (?)");
        mnGame.add(mnMarks);

        mnColor.setSelected(true);
        mnColor.setText("Color");
        mnGame.add(mnColor);

        mnSound.setText("Sound");
        mnGame.add(mnSound);
        mnGame.add(jSeparator3);

        mnBestTimes.setText("Best Times...");
        mnGame.add(mnBestTimes);
        mnGame.add(jSeparator4);

        mnExit.setText("Exit");
        mnGame.add(mnExit);

        mnBar.add(mnGame);

        mnHelp.setMnemonic('H');
        mnHelp.setText("Help");

        mnContents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnContents.setText("Contents");
        mnHelp.add(mnContents);

        mnSearchHelp.setText("Search for Help on...");
        mnHelp.add(mnSearchHelp);

        mnUsingHelp.setText("Using Help");
        mnHelp.add(mnUsingHelp);
        mnHelp.add(jSeparator5);

        mnAbout.setText("About Minesweeper...");
        mnHelp.add(mnAbout);

        mnBar.add(mnHelp);

        setJMenuBar(mnBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-170)/2, (screenSize.height-260)/2, 170, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void mnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNewActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "yoi!","",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnNewActionPerformed

    private void btnSmileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSmileMousePressed
        // TODO add your handling code here:
        btnSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smiley2.png")));
        
    }//GEN-LAST:event_btnSmileMousePressed

    private void btnSmileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSmileMouseReleased
        // TODO add your handling code here:
        btnSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smiley1.png")));
    }//GEN-LAST:event_btnSmileMouseReleased

    private void mnBeginnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBeginnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnBeginnerActionPerformed

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        this.isRunning = true;
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        //if (evt.getButton() == BUTTON2);
        
    }//GEN-LAST:event_jLabel2MousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex){
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSweep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSmile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JRadioButtonMenuItem mnBeginner;
    private javax.swing.JMenuItem mnBestTimes;
    private javax.swing.JCheckBoxMenuItem mnColor;
    private javax.swing.JMenuItem mnContents;
    private javax.swing.JRadioButtonMenuItem mnCustom;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JRadioButtonMenuItem mnExpert;
    private javax.swing.JMenu mnGame;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JRadioButtonMenuItem mnIntermediate;
    private javax.swing.JCheckBoxMenuItem mnMarks;
    private javax.swing.JMenuItem mnNew;
    private javax.swing.JMenuItem mnSearchHelp;
    private javax.swing.JCheckBoxMenuItem mnSound;
    private javax.swing.JMenuItem mnUsingHelp;
    private javax.swing.JPanel pnGame;
    private javax.swing.JPanel pnToolbar;
    private javax.swing.JTextField txtMines;
    private javax.swing.JTextField txtTimes;
    // End of variables declaration//GEN-END:variables

    public void setDuration(){

        if(isRunning){
            s++;
        }
        if (s==999){
            isRunning = false;
        }

        Time t = new Time();
        TimeEntity te = t.timeFormat(s, m, h);

        if (Integer.parseInt(te.getDetik()) <= 99){
            txtTimes.setText("0" + te.getDetik());
        }else{
            txtTimes.setText(te.getDetik());
        }
    }

}
